config/routes.rb
Rails.application.routes.draw do
  get 'subscription_payment_watches/index'

  root 'home_pages#home'

  # home
  get '/contact', to: 'home_pages#contact'
  get '/about', to: 'home_pages#about'
  get '/privacy', to: 'home_pages#privacy'  
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # resources 
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :movies,              except: [:destroy] do
    member do
      patch :release, to: 'movies#release'
    end
  end
  resources :tv_shows,              except: [:destroy, :create, :new]
  resources :movie_interests,      only: [:create, :destroy]
  post '/create_from_tmdb',       to: 'movies#create_from_tmdb'
  post '/create_tv_from_tmdb',       to: 'tv_shows#create_from_tmdb'
  resources :tmdb_movies,         only: [:index, :show]
  resources :tmdb_tv_shows,       only: [:index, :show]  
  resources :subscriptions,       except: [:destroy]  do
    resources :watches, only: [:index], to: 'subscription_watches#index'
  end
  resources :locations,           except: [:destroy, :show]
  resources :subscription_payments, only: [:edit, :update]  do
    resources :watches, only: [:index], to: 'subscription_payment_watches#index'
  end
  resources :watches do
    get :friends, to: 'watches#friends'   
  end
  resources :watch_likes,         only: [:create, :destroy]
  delete 'friends/destroy'
  resources :friend_requests
  get '/friend_feed', to: 'friend_watches#index'
  
  # charts
  namespace :charts do 
    namespace :users do 
      namespace :watches do 
        get 'watch'
        get 'location_cinema'
        get 'rating'
      end
      namespace :subscriptions do
        get 'watch'
      end
    end
    namespace :application do
      namespace :movies do
      end
    end
  end
  
  # upcoming movies
  get 'upcoming_movies', to: 'upcoming_movies#index'
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  before_action :logged_in_user, except: [:show, :index]

  def index
    if params[:keywords].present?
      @movies = search_movies
      @keywords = params[:keywords]
    else
      @movies = Movie.all.order(:title).paginate(page: params[:page])
    end
  end

  def show
    id = params[:id]
    @movie = Movie.find_by(id: id)
    @average_rating = Movie.average_rating(id)
    @total_watches = Movie.total_watches(id)
    @last_reviews = Movie.last_reviews(id, 3)
    @user_watches = Watch.details.where(user_id: current_user.id, movie_id: id) if logged_in?
    @watched_redirect = params[:watched].present?
  end

  def create
    @movie = Movie.new(movie_params)
    save_movie
  end

  def create_from_tmdb
    if params[:tmdb_id].present?
      @movie = MovieImporter.import(params[:tmdb_id])
      if params[:redirect_show] == 'true'
        flash[:success] = 'movie refreshed'
        redirect_to @movie
      else
        flash[:success] = 'movie added'
        redirect_to movies_path
      end
    else
      redirect_to movies_path
    end
  end

  def edit
    @movie = Movie.find_by(id: params[:id])
    @upcoming = params[:upcoming]
  end

  def update
    @movie = Movie.find_by(id: params[:id])
    if @movie.update_attributes(movie_params)
      flash[:success] = 'movie updated'
      if params[:movie][:upcoming] == "true" 
        redirect_to upcoming_movies_path
      else
        redirect_to movies_path
      end
    else
      render 'edit'
    end
  end

  def new
    @movie = Movie.new

    if params[:tmdb_id].present?
      set_movie_defaults(params[:tmdb_id])
    end
  end

  def release
    @movie = Movie.find_by(id: params[:id])
    @movie.released = true
    if @movie.save 
      flash[:success] = 'movie release status updated'
    else
      flash[:danager] = @movie.errors.full_messages
    end
    redirect_to upcoming_movies_path
  end

  private

    def movie_params
      params.require(:movie).permit(:title, :year, :imdb_id, :tmdb_id, :tmdb_poster_path,
        :released, :release_date)
    end

    def movie_service
      @movie_service ||= MovieDbService.new
    end

    def set_movie_defaults(tmdb_id)
      movie = movie_service.movie(params[:tmdb_id])
      @movie.title = movie['title']
      @movie.year = year_for_movie(movie)
      @movie.tmdb_id = tmdb_id
      @movie.imdb_id = movie['imdb_id']
      @movie.tmdb_poster_path = movie['poster_path']
    end

    def save_movie
      if @movie.save
        flash[:success] = 'movie created'
        redirect_to movies_path
      else
        render 'new'
      end
    end

    def search_movies
      Movie.where('lower(title) LIKE :keyword',
        keyword: '%' + params[:keywords].downcase + '%').order(:title).paginate(
          page: params[:page])
    end
end

app/helpers/movies_helper.rb
# frozen_string_literal: true

module MoviesHelper
  def people_text(count)
    base_text = 'people'
    count == 1 ? base_text.singularize : base_text
  end
end

app/views/movies/_movie.html.erb
<div class="col-sm-6">
  <li class="list-group-item clearfix">
      <div class="row">
    	<div class="col-sm-2">
    	   <%= poster_for_path movie.tmdb_poster_path, movie.title %>
    	</div>
      <div class="col-sm-10">
        <h4><%= link_to movie.title, movie %></h4>
        <p><%= "#{movie.year}" %></p>
        <hr style="margin-bottom: 0.5em;">
        <span class="pull-left">
          <% if logged_in? %>
            <div class="row">
              <div  class="col-xs-3">
                <%= link_to "<button type=\"button\"><i class=\"fa fa-pencil-square-o\"></i></button>".html_safe, edit_movie_path(movie.id)%>
              </div>
              <div  class="col-xs-3">
                <%= link_to "<button type=\"button\"><i class=\"fa fa-eye\"></i></button>".html_safe, new_watch_path(movie_id: movie.id)%>
              </div>
              <div  class="col-xs-3">
              </div>
                  </div> 
          <% end %>
        </span>
    
      </div>
  </li>
</div>

app/views/movies/_movie_form.html.erb
<%= form_for(@movie) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', autofocus: true %>

  <%= f.label :year %>
  <%= f.text_field :year, class: 'form-control' %>
  <%= f.label :released do %>
    <span>Released</span>
    <%= f.check_box :released %>
   <% end %><br>
  <%= f.label :release_date %>
  <%= f.date_field :release_date, class: 'form-control' %>
  

        
  <%= f.hidden_field :tmdb_id %>
  <%= f.hidden_field :imdb_id %>
  <%= f.hidden_field :tmdb_poster_path %>
  <%= f.hidden_field :upcoming, value: @upcoming %>
  
  <div class="row">    
    <div class="col-sm-6">
      <%= f.submit "save", class: "btn btn-primary" %>
    </div>
    <div class="col-sm-6">
      <%= link_to "cancel", if @upcoming then upcoming_movies_path else movies_path end, 
        method: :get, class: "btn btn-default form-control" %>
    </div>
  </div>
<% end %>

app/views/movies/edit.html.erb
<% provide(:title, 'edit movie') %>
<div class="container">
<h4><%= "edit #{@movie.title}" %></h4>
<div class="row">
  <div class="col-md-3">
    <%= poster_for_path @movie.tmdb_poster_path, @movie.title, size: 200 %>
  </div>

  <div class="col-md-8">
      <%= render 'movie_form' %>
  </div>
</div>
</div>

app/views/movies/index.html.erb
<% provide(:title, 'movies') %>
<div class="container">
  <div class="media-list my-3">
    <div class="row">
      <div class="col-sm-9">
        <%= form_for :movies, method: :get do |f| %>
          <div class="input-group input-group-lg">
            <%= label_tag :keywords, nil, class: "sr-only" %>
            <%= text_field_tag :keywords, @keywords, 
                  placeholder: "Movie Title", 
                  class: "form-control input-lg" %>
            <span class="input-group-btn">
              <%= submit_tag "find movies", class: "btn btn-primary btn-lg" %>
            </span>
          </div>
        <% end %>
      </div>
      <div class="col-sm-3">
        <% if logged_in? %>
          <br>
          <%= link_to "add new movie", tmdb_movies_path(keywords: @keywords) %>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="media-list my-1">
    <hr>
      <% @movies.each do |movie| %>
        <div class="card media-card my-3">
          <div class="media-poster"><%= poster_for_path movie.tmdb_poster_path, movie.title, size: 500, class: "card-img rounded-0"  %></div>
          <div class="card-body">
            <% if logged_in? %>
              <%= link_to new_watch_path(movie_id: movie.id), class: "rounded-pill ml-auto media-rating" do %>
                <i class="fa fa-eye"></i>
              <% end %>
            <% end %>            
            <h5 class="card-title"><%= link_to movie.title, movie %></h5>
            <h6 class="card-subtitle mb-2"><%= movie.tagline %></h6>
            <p class="card-text"><%= truncate(movie.overview, length: 200) %></p>
            <% if logged_in? %>
              <hr style="margin-bottom: 0.5em;">
              <div class="container">
                <div class="row my-1">
                  <div  class="col-sm-1">
                    <%= link_to "<button type=\"button\" class=\"rounded-pill small_icon_button\"><i class=\"fa fa-pencil-square-o\"></i></button>".html_safe, edit_movie_path(movie.id) %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
  
        </div>  
       <% end %>      
  </div>
  
  <div class="digg_pagination">
  <%= will_paginate @movies %>
  </div>
</div>
</div>

app/views/movies/new.html.erb
<% provide(:title, 'new movie') %>
<div class="row">
  <div class="col-md-3">
    <%= poster_for_path @movie.tmdb_poster_path, @movie.title, size: 200 %>
  </div>  
  <div class="col-md-6">
      <%= render 'movie_form' %>
  </div>
</div>

app/views/movies/show.html.erb
<% provide(:title, 'movie') %>

<div class="media-banner">
  <div class="container">
   <ol class="breadcrumb">  
      <% if @watched_redirect %>
        <li class="breadcrumb-item"><%= link_to "Watches", watches_path %></li>
      <% else %>
        <li class="breadcrumb-item"><%= link_to "Movies", movies_path %></li>
      <% end %>
      <li class="breadcrumb-item active" aria-current="page">Movie</li>
    </ol>
  </div>  
  <figure class="backdrop">
    <%= background_for_path(@movie.backdrop_path, @movie.title) %>
  </figure>

  <div class="container">
    <div class="row my-4">
      <div class="col-md-3">
        <%= poster_for_path @movie.tmdb_poster_path, @movie.title, size: 500, class: "poster"  %>
      </div>

      <div class="col-md-9">
        <div class="media-info">
          <h2 class="media-rating"><%= @average_rating  %></h2>

          <h1 class="mb-4"><%= @movie.title %></h1>

          <h5>Overview</h5>
          <p><%= @movie.overview %></p>

          <%= link_to "IMDb", @movie.imdb_url, target: "_blank", class: "btn btn-light rounded-pill" if @movie.imdb_id? %>
          <%= link_to "TMDb", @movie.tmdb_url, target: "_blank", class: "btn btn-info rounded-pill" if @movie.tmdb_id? %>
          <%= link_to new_watch_path(movie_id: @movie.id), class: "btn btn-danger rounded-pill" do %>
            <i class="fa fa-eye"></i>
            Watch
          <% end %>
          <%= link_to "Refresh", create_from_tmdb_path(tmdb_id: @movie.tmdb_id, redirect_show: true), method: :post, class: "btn btn-success rounded-pill" if @movie.tmdb_id? %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container my-4">
  <ul class="nav nav-tabs">
    <li class="nav-item"><%= link_to "Reviews", "#review", class: "nav-link active", data: { toggle: "tab" } %></li>
    <li class="nav-item"><%= link_to "Watches ", "#watches", class: "nav-link", data: { toggle: "tab" } %></li>  
  </ul>

  <div class="tab-content">
    <div class="tab-pane fade show active" role="tabpanel" id="review">
      <% @last_reviews.each do |review| %>
        <div class="card media-card my-3">
          <div class="card-body">
            <h5 class="card-title"><%= review.date %></h5>
            <h6 class="card-subtitle mb-2">Rating: <%= review.rating %></h6>
            <p class="card-text"><%= review.review %></p>
          </div>
        </div>  
       <% end %>       
    </div>

    <div class="tab-pane fade" role="tabpanel" id="watches">
      <div class="card media-card my-3">
        <div class="card-body">
          <% if @user_watches %>
            <% @user_watches.each do |u| %>
              <%= link_to edit_watch_path(id: u.id) do %>
                Watched on <%= u.date %>
              <% end %>
              </br>
            <% end %>
          <% else %>
            <p>Login to see when you watched this movie.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>