config/routes.rb
Rails.application.routes.draw do
  get 'subscription_payment_watches/index'

  root 'home_pages#home'

  # home
  get '/contact', to: 'home_pages#contact'
  get '/about', to: 'home_pages#about'
  get '/privacy', to: 'home_pages#privacy'  
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # resources 
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :movies,              except: [:destroy] do
    member do
      patch :release, to: 'movies#release'
    end
  end
  resources :tv_shows,              except: [:destroy, :create, :new]
  resources :movie_interests,      only: [:create, :destroy]
  post '/create_from_tmdb',       to: 'movies#create_from_tmdb'
  post '/create_tv_from_tmdb',       to: 'tv_shows#create_from_tmdb'
  resources :tmdb_movies,         only: [:index, :show]
  resources :tmdb_tv_shows,       only: [:index, :show]  
  resources :subscriptions,       except: [:destroy]  do
    resources :watches, only: [:index], to: 'subscription_watches#index'
  end
  resources :locations,           except: [:destroy, :show]
  resources :subscription_payments, only: [:edit, :update]  do
    resources :watches, only: [:index], to: 'subscription_payment_watches#index'
  end
  resources :watches do
    get :friends, to: 'watches#friends'   
  end
  resources :watch_likes,         only: [:create, :destroy]
  delete 'friends/destroy'
  resources :friend_requests
  get '/friend_feed', to: 'friend_watches#index'
  
  # charts
  namespace :charts do 
    namespace :users do 
      namespace :watches do 
        get 'watch'
        get 'location_cinema'
        get 'rating'
      end
      namespace :subscriptions do
        get 'watch'
      end
    end
    namespace :application do
      namespace :movies do
      end
    end
  end
  
  # upcoming movies
  get 'upcoming_movies', to: 'upcoming_movies#index'
end

app/controllers/upcoming_movies_controller.rb
class UpcomingMoviesController < ApplicationController
  def index
    @upcoming_movies = Movie.where(released: false).order(:release_date, :title).paginate(page: params[:page])

    if logged_in?
      @movie_interests = MovieInterest.where(user_id: current_user.id).where(
        movie_id: @upcoming_movies.pluck(:id)) if @upcoming_movies
    end
  end
end

app/helpers/upcoming_movies_helper.rb
module UpcomingMoviesHelper
end

app/views/upcoming_movies/_interested.html.erb
<%= link_to "<button type=\"button\" class=\"rounded-pill small_icon_button\"><i class=\"fa fa-bell\"></i></button>".html_safe, 
  movie_interest_path(movie_interest.id), method: :delete, remote: true %>

app/views/upcoming_movies/_not_interested.html.erb
<%= link_to "<button type=\"button\" class=\"rounded-pill small_icon_button\"><i class=\"fa fa-bell-o\"></i></button>".html_safe, 
  movie_interests_path(movie_id: movie_id), method: :post, remote: true %>

app/views/upcoming_movies/_upcoming_movie.html.erb
<% movies.each do |movie| %>
  <div class="card media-card my-3">
    <div class="media-poster"><%= poster_for_path movie.tmdb_poster_path, movie.title, size: 500, class: "card-img rounded-0"  %></div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to movie.title, movie %></h5>
      <h6 class="card-subtitle mb-2"><%= movie.tagline %></h6>
      <p class="card-text"><%= truncate(movie.overview, length: 200) %></p>

      <% if logged_in? %>
        <hr style="margin-bottom: 0.5em;">
        <div class="container">
          <div class="row my-1">
            <div  class="col-xs-1">
              <%= link_to "<button type=\"button\" class=\"rounded-pill small_icon_button\"><i class=\"fa fa-pencil-square-o\"></i></button>".html_safe, edit_movie_path(movie.id, params: {upcoming: true})%>
            </div>
            <div class="col-xs-1" id="interested_state_<%= movie.id %>">
          	  <% if movie_interest = @movie_interests.detect { |mi| mi.movie_id == movie.id } %>
      	        <%= render 'interested', movie_interest: movie_interest %>
          	  <% else %>
                <%= render 'not_interested', movie_id: movie.id %>
          	  <% end %>
  	        </div>

            <div  class="col-xs-1">
              <%= link_to "<button type=\"button\" class=\"rounded-pill small_icon_button\"><i class=\"fa fa-check\"></i></button>".html_safe, release_movie_path(id: movie.id), method: :patch %>
            </div>
          
          </div>
        </div>
      <% end %>
    
    </div>
  </div>  
<% end %>

app/views/upcoming_movies/index.html.erb
<% provide(:title, 'upcoming movies') %>
<div class="container">
  <div class="media-list my-1">
    <hr>
    <%= render 'upcoming_movie', movies: @upcoming_movies %>
  </div>
  <div class="digg_pagination">
    <%= will_paginate @movies %>
  </div>
</div>