config/routes.rb
Rails.application.routes.draw do
  get 'subscription_payment_watches/index'

  root 'home_pages#home'

  # home
  get '/contact', to: 'home_pages#contact'
  get '/about', to: 'home_pages#about'
  get '/privacy', to: 'home_pages#privacy'  
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # resources 
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :movies,              except: [:destroy] do
    member do
      patch :release, to: 'movies#release'
    end
  end
  resources :tv_shows,              except: [:destroy, :create, :new]
  resources :movie_interests,      only: [:create, :destroy]
  post '/create_from_tmdb',       to: 'movies#create_from_tmdb'
  post '/create_tv_from_tmdb',       to: 'tv_shows#create_from_tmdb'
  resources :tmdb_movies,         only: [:index, :show]
  resources :tmdb_tv_shows,       only: [:index, :show]  
  resources :subscriptions,       except: [:destroy]  do
    resources :watches, only: [:index], to: 'subscription_watches#index'
  end
  resources :locations,           except: [:destroy, :show]
  resources :subscription_payments, only: [:edit, :update]  do
    resources :watches, only: [:index], to: 'subscription_payment_watches#index'
  end
  resources :watches do
    get :friends, to: 'watches#friends'   
  end
  resources :watch_likes,         only: [:create, :destroy]
  delete 'friends/destroy'
  resources :friend_requests
  get '/friend_feed', to: 'friend_watches#index'
  
  # charts
  namespace :charts do 
    namespace :users do 
      namespace :watches do 
        get 'watch'
        get 'location_cinema'
        get 'rating'
      end
      namespace :subscriptions do
        get 'watch'
      end
    end
    namespace :application do
      namespace :movies do
      end
    end
  end
  
  # upcoming movies
  get 'upcoming_movies', to: 'upcoming_movies#index'
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  default_scope { includes(:subscription_period, :payment_type) }

  belongs_to :user
  belongs_to :subscription_period
  belongs_to :payment_type, optional: true
  has_many  :subscription_payments
  has_many  :watches

  validates :name, presence: true, length: { maximum: 75 }
  validates :amount, presence: true
  validates :start_date, presence: true

  validate  :end_date_after_start_date?

  def end_date_after_start_date?
    return if [start_date.blank?, end_date.blank?].any?
    if start_date > end_date
      errors.add(:end_date, 'end date must be after start date')
    end
  end

  def self.subscriptions_for_user(user_id)
    Subscription.where(user_id: user_id).order(:name)
  end

  def self.subscriptions_due
    today = Date::today
    Subscription.where(next_due_date: nil).or(
      Subscription.where('next_due_date <= ?', today)).where(
        'end_date is null OR end_date >= ?', today)
  end
end

app/controllers/charts/users/subscriptions_controller.rb
# frozen_string_literal: true

class Charts::Users::SubscriptionsController < ApplicationController
  def watch
    subscriptions = Subscription.where(user_id: current_user.id)
    render json: subscriptions.map { |sub| { name: sub.name,
      data: sub.watches.group_by_month(:date).count } }
  end
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  before_action :logged_in_user

  def index
    @subscriptions = Subscription.all.where(user_id: current_user.id).order(:name)
  end

  def show
    find_subscription
    redirect_to subscriptions_path and return if @subscription.nil?
    @total_watches = Watch.where(subscription_id: @subscription.id).count
    @total_subs = SubscriptionPayment.where(subscription_id: @subscription.id).sum(:amount)
    @total_full_price = SubscriptionPayment.where(subscription_id: @subscription.id).sum('full_price_amount * watches_count')
    @watch_by_years = Watch.where(subscription_id: @subscription.id).group_by_year(:date).count
    @subscription_payments = SubscriptionPayment.where(
      subscription_id: @subscription.id).order(start_date: :desc).paginate(
        page: params[:page])
  end

  def edit
    find_subscription
    redirect_to subscriptions_path and return if @subscription.nil?
  end

  def update
    find_subscription
    redirect_to subscriptions_path and return if @subscription.nil?
    if @subscription.update_attributes(subscription_params)
      flash[:success] = 'subscription updated'
      redirect_to subscriptions_path
    else
      render 'edit'
    end
  end

  def new
    @subscription = Subscription.new
  end

  def create
    subscription = Subscription.new(subscription_params)
    subscription.user_id = current_user.id
    if subscription.save
      flash[:success] = 'subscription created'
      redirect_to subscriptions_path
    else
      @subscription = subscription
      render 'new'
    end
  end

  private

    def subscription_params
      params.require(:subscription).permit(:name, :amount, :start_date, :end_date,
        :reference, :subscription_period_id, :payment_type_id, :full_price_amount)
    end

    def find_subscription
      @subscription = Subscription.find_by(user_id: current_user.id, id: params[:id])
    end
end

app/helpers/subscriptions_helper.rb
# frozen_string_literal: true

module SubscriptionsHelper
  def cost_per_movie(amount, watches_count)
    (amount / watches_count).round(2) if watches_count != nil && watches_count > 0
  end

  def total_full_price(full_price_amount, watches_count)
    (full_price_amount * watches_count).round(2) if full_price_amount != nil && watches_count != nil
  end

  def total_savings(amount, full_price_amount, watches_count)
    total_full_price_amount = total_full_price(full_price_amount, watches_count)
    ((total_full_price_amount || 0) - amount).round(2)
  end
end

app/views/subscriptions/_subscription.html.erb
<tr>
  <td>
    <%= link_to "<button type=\"button\" class=\"rounded-pill small_icon_button\"><i class=\"fa fa-pencil-square-o\"></i></button>".html_safe, 
      edit_subscription_path(subscription.id)%>
  </td>     
  <td><%= link_to subscription.name, subscription %></td>
  <td><%= subscription.amount %></td>
  <td><%= subscription.next_due_date %></td>  
  <td class="hidesmall"><%= subscription.start_date %></td>
  <td class="hidesmall"><%= subscription.end_date %></td>  
</tr>

app/views/subscriptions/_subscription_form.html.erb
<%= form_for(@subscription) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', autofocus: true %>
 
  <%= f.label :reference %>
  <%= f.text_field :reference, class: 'form-control' %>
  
  <%= f.label :amount %>
  <%= f.number_field :amount, in: 0.0..10000.0, step: 0.01, class: 'form-control' %>
 
  <%= f.label :full_price_amount %>
  <%= f.number_field :full_price_amount, in: 0.0..10000.0, step: 0.01, class: 'form-control' %>  
 
  <%= f.label :subscription_period_id %>
  <%= collection_select(:subscription, :subscription_period_id, 
    LookUpService.lookup_values(:subscription_periods), :id, :name, {include_blank: true}, 
    {class: 'form-control'}) %>
  <div class="row">    
    <div class="col-sm-6">   
      <%= f.label :start_date %>
      <%= f.date_field :start_date, class: 'form-control' %>
    </div>
    <div class="col-sm-6"> 
      <%= f.label :end_date %>
      <%= f.date_field :end_date, class: 'form-control' %>
    </div>
  </div>
  
  <%= f.label :payment_type_id %>  
  <%= collection_select(:subscription, :payment_type_id, 
    LookUpService.lookup_values(:payment_types), :id, :name, {include_blank: true}, 
    {class: 'form-control'}) %>  
    
  <div class="row">    
    <div class="col-sm-6">
      <%= f.submit "save", class: "btn btn-primary" %>
    </div>
    <div class="col-sm-6">
      <%= link_to "cancel", subscriptions_path, method: :get, class: "btn btn-default form-control" %>
    </div>
  </div>
<% end %>

app/views/subscriptions/_year_table_row.html.erb
<b><%= watch_year.year%>:</b> <%= watch_count%>
<br>

app/views/subscriptions/edit.html.erb
<% provide(:title, 'edit subscription') %>
<div class="container">
  <div class="media-list my-1">
    <%= render 'subscription_form' %>
  </div>
</div>

app/views/subscriptions/index.html.erb
<% provide(:title, 'your subscriptions') %>
<div class="container">
    <div class="media-list my-3">
    <%= link_to "add new subscription", new_subscription_path %>
    
    <table class="table">
        <tr>
        <th/>          
        <th>name</th>
        <th>amount</th> 
        <th>next due</th>
        <th class="hidesmall">start</th>
        <th class="hidesmall">end</th>
      </tr>
      <%= render @subscriptions %>
    </table>
    </div>
</div>

app/views/subscriptions/new.html.erb
<% provide(:title, 'new subscription') %>
<div class="container">
  <div class="media-list my-1">
    <%= render 'subscription_form' %>
  </div>
</div>

app/views/subscriptions/show.html.erb
<% provide(:title, 'subscription') %>

<!--Photo by Skitterphoto from Pexels-->
<div class="media-banner">
  <div class="container">
    <ol class="breadcrumb">  
      <li class="breadcrumb-item"><%= link_to "Subscriptions", subscriptions_path %></li>
      <li class="breadcrumb-item active" aria-current="page">Subscription</li>
    </ol>
  </div>    
  <figure class="backdrop">
    <%= image_tag("watch_background.jpg") %>
  </figure>

  <div class="container">
    <div class="row my-4">

      <div class="col-md-9">
        <div class="media-info">
            <b>name:</b> <%= @subscription.name %> 
            <br>
            <b>next due:</b> <%= @subscription.next_due_date %>
            <br>
            <b>total movies watched:</b> <%= link_to @total_watches, subscription_watches_path(subscription_id: @subscription.id) %>
            <br>
            <b>total cost:</b> <%= @total_subs %>
            <br>
            <b>total full price:</b> <%= @total_full_price %>
            <br>
            <b>total savings:</b> <%= @total_full_price - @total_subs %>
            <br>       
            <b>average price per watch:</b> <%= cost_per_movie(@total_subs, @total_watches) %>
        </div>      
      </div>
    </div>
  </div>
</div>
<div class="container my-4">
  <ul class="nav nav-tabs">
    <li class="nav-item"><%= link_to "Payments", "#payment", class: "nav-link active", data: { toggle: "tab" } %></li>
    <li class="nav-item"><%= link_to "Watches Per Year ", "#watches", class: "nav-link", data: { toggle: "tab" } %></li>
  </ul>
  
   <div class="tab-content">
    <div class="tab-pane fade show active" role="tabpanel" id="payment"> 
      <table class="table">
          <tr>
            <th></th>
            <th>start date</th>
            <th class="hidesmall">end date</th> 
            <th class="hidesmall">amount</th>
            <th>watched</th>
            <th>average price</th>
            <th class="hidesmall">full price</th>
            <th>savings</th>
          </tr>
          <%= render @subscription_payments %>
        </table>
        <div class="digg_pagination">
        <%= will_paginate @subscription_payments %>
        </div>
    </div>
    <div class="tab-pane fade" role="tabpanel" id="watches">
      <% @watch_by_years.each do |watch_year, watch_count| %>
        <%= render 'year_table_row', watch_year: watch_year, watch_count: watch_count %>
      <% end %>  
    </div>
  </div>
</div>